name: Auto Assign

on:
  pull_request:
    types: ['opened', 'ready_for_review']

permissions:
  contents: read
  pull-requests: write

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.2.5
