name: CI

on:
  push:
    branches: ['main', 'dev']
  pull_request:
  workflow_call:

jobs:
  ci:
    runs-on: ubuntu-latest

    env:
      NEXT_PUBLIC_API_BASE_URL: ${{ vars.DEV_API_BASE_URL }}

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.17.1'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Check type
        run: npm run type:check

      - name: Linting
        run: npm run lint

      - name: Check code format
        run: npm run format:check
