name: Deploy Gnimty(dev)

on:
  push:
    branches: ['dev']

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  deploy-setup:
    needs: ci

    runs-on: ubuntu-latest
    outputs:
      docker_image: ${{ steps.write-vars.outputs.docker_image }}
      container_name: ${{ steps.write-vars.outputs.container_name }}
    steps:
      - id: write-vars
        run: |
          echo "docker_image=${{ vars.DOCKER_IMAGE_NAME }}:dev" >> "$GITHUB_OUTPUT"
          echo "container_name=${{ vars.DOCKER_IMAGE_NAME }}-dev" >> "$GITHUB_OUTPUT"

  deploy:
    needs: deploy-setup

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Copy files
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          source: '*'
          target: ${{ vars.DEPLOY_PATH }}
          rm: true

      - name: Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd ${{ vars.DEPLOY_PATH }}
            docker build . -t ${{ needs.deploy-setup.outputs.docker_image }}
            docker stop ${{ needs.deploy-setup.outputs.container_name }}
            docker run -p 3000:3000 -d --name=${{ needs.deploy-setup.outputs.container_name }} ${{ needs.deploy-setup.outputs.docker_image }}
