name: Deploy

on:
  push:
    barnches:
      - test/actions/main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm i

      - name: Build Next.js
        run: npm run build

      - name: Deploy to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PEM }}
          source: '.next/*'
          target: '/home/ubuntu/next.js/frontend'

      - name: Install dependencies & Start on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PEM }}
          script: |
            cd /home/ubuntu/next.js/frontend
            npm install
            pm2 restart all
